prefetch_factor: 2
pin_memory: True

read_group_size: ${hardware.num_gpus_per_model}
select_in: ${data.in_lres_variables}
select_in_hres: ${data.forcing}
select_out: ${data.out_hres_variables}

dataset:
  zip:
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_x}
      name: lres
      select: ${dataloader.select_in}
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_y}
      name: hres
      select: ${dataloader.select_in_hres}
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_y}
      name: out
      select: ${dataloader.select_out}
  adjust: dates

num_workers:
  training: 6
  validation: 6
  test: 6
  predict: 2

limit_batches:
  training: null
  validation: null
  test: 20
  predict: 20

batch_size:
  training: 1
  validation: 1
  test: 1
  predict: 1

training:
  start: 1996-01-01T00:00:00
  end: 2018-12-31T23:00:00
  frequency: ${data.frequency}
  dataset: ${dataloader.dataset}

validation:
  start: 2019-01-01T00:00:00
  end: 2019-12-31T23:00:00
  frequency: ${data.frequency}
  dataset: ${dataloader.dataset}

test:
  start: 2020-01-01T00:00:00
  end: 2023-12-31T21:00:00
  frequency: ${data.frequency}
  dataset: ${dataloader.dataset}

hres_grid_indices:
  _target_: anemoi.training.data.grid_indices.FullGrid
  nodes_name: ${graph.data}

grid_indices:
  _target_: anemoi.training.data.grid_indices.FullGrid
  nodes_name: ${graph.data}

lres_grid_indices:
  _target_: anemoi.training.data.grid_indices.FullGrid
  nodes_name: ${graph.lres}
